### ISSUE TITLE
Allow a threshold below which results are not returned

### ISSUE THREAD

**Issue by mikejsdev** [fwextensions/quick-score#14]
This is a really great library, thanks!

It would be useful if the user could specify a minimum score, below which results are not returned.

This would help with performance for those of us using this on large data sets.

Thanks,
Mike

**Comment by fwextensions** [comment]
Sorry for the slow response!

There is indeed a `minimumScore` value that can be passed in the `options` object to the `QuickScore` constructor, as described in the [API docs](https://fwextensions.github.io/quick-score/QuickScore.html):

> `minimumScore`
> An optional value that specifies the minimum score an item must have to appear in the results array returned from search(). Defaults to 0, so items that don't match the full query will not be returned. This value is ignored if the query is empty or undefined, in which case all items are returned, sorted alphabetically and case-insensitively on the sortKey, if any.

You'd use it like this:

```
const qs = new QuickScore(myItems, { minimumScore: .2 });
```

This will help to filter down the list if you want to require a closer match for an item to appear.  However, I'm not sure it will help dramatically with performance.  Every item in the data set will still get matched against the query.  Marginal matches won't get added to the results list, though, which will reduce memory usage when returning the list and may help the performance slightly.

**Comment by mikejsdev** [comment]
Thanks for getting back to me.

Not sure how I missed that in the docs, my apologies. This feature works well, really great library!!

I'll close this issue.
