### ISSUE TITLE
Question about original QuickSilver algorithim

### ISSUE THREAD

**Issue by MitchellMarkGeorge** [fwextensions/quick-score#24]
In the README you mention that this implementation is based on the Quicksilver algorithm. Do you mind including a source to go to because I can't seem to fins anything about it anywhere.

**Comment by fwextensions** [comment]
[Quicksilver](https://qsapp.com/about.php) is an autocompleting file launcher on macOS that was around long before Spotlight, Raycast, etc.  

I initially ported `quick-score` from the original Objective C code, though that page seems to be long gone.  The current matching code is available in the [Quicksilver repo](https://github.com/quicksilver/Quicksilver), in [QSSense.m](https://github.com/quicksilver/Quicksilver/blob/main/Quicksilver/Code-QuickStepFoundation/QSSense.m).
