### ISSUE TITLE
Distribute as a JavaScript file?

### ISSUE THREAD

**Issue by Jos512** [fwextensions/quick-score#4]
Hi!

QuickScore looks very impressive and I really like how minimal it is. But I'm wondering if you can also distribute it as a ready JavaScript file?

My project doesn't use npm/node, and trying to build from the repository's source gives all kinds of errors on my computer. I tried to solve most of them, but I'm not that good at npm/node and the likes.

Yet I still would like and try to use QuickScore for my static website. :slightly_smiling_face:

**Comment by fwextensions** [comment]
unpkg.com is a great CDN that lets you easily reference any npm package via a `<script>` tag.  You can see all of the built files here: https://unpkg.com/browse/quick-score/dist/

You can either download the code and use the copy in your website or link to it.  `quick-score.esm.min.js` is a minified ES6 module, while `quick-score.min.js` is a UMD module.  It'll export everything on a `quickScore` global if you're not using an AMD packager like RequireJS.

If you want to link it on the CDN, you'll probably want to include a version number in the URL, like `https://unpkg.com/quick-score@0.0.6/dist/quick-score.min.js`.

I'm curious what errors you're getting.  If you have `npm` installed, you should be able to run these commands to build the files in the `dist/` folder:

    npm install quick-score
    npm run build

**Comment by Jos512** [comment]
Thanks for the quick and thorough reply! I didn't know that unpkg automatically (?) makes JavaScript files from repositories, although I did hear about unpkg earlier.

This solves my issue since I can use those files. :+1: 

---

For completeness, if I run those two commands, I get this output:

~~~
C:\Temp\QuickScore-test>npm install quick-score
C:\Temp\QuickScore-test
`-- quick-score@0.0.6

npm WARN enoent ENOENT: no such file or directory, open 'C:\Temp\QuickScore-test\package.json'
npm WARN QuickScore-test No description
npm WARN QuickScore-test No repository field.
npm WARN QuickScore-test No README data
npm WARN QuickScore-test No license field.

C:\Temp\QuickScore-test>npm run build
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Temp\QuickScore-test\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Temp\QuickScore-test\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Temp\QuickScore-test\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Temp\QuickScore-test\npm-debug.log
~~~

I'm pretty sure this has nothing to do with QuickSort but rather with my Node version, which is pretty old. Unfortunately there are several legacy projects on my computer that I still need to maintain so I'm very much off putting doing an update and breaking all kinds of things.

I'll close the issue since my original query is solved and you don't need to look further into this. I'm all set. :slightly_smiling_face:

**Comment by fwextensions** [comment]
Glad unpkg will work for you.

I was wrong about the commands.  Not sure what I was thinking.  All you need to do is `npm install quick-score`, and then the built files will be in `node_modules/quick-score/dist`, the same ones that I mentioned above as available on unpkg.  You can then copy whichever version of the built lib you want to use over to your project.
