### ISSUE TITLE
quickScore is not defined

### ISSUE THREAD

**Issue by alvise** [fwextensions/quick-score#6]
Hi,
i included the script from unpkg like this:
<script src="https://unpkg.com/browse/quick-score@0.0.7/dist/quick-score.js"></script>
(I tried also 0.6)

but this is the result when i try to call it in console:

quickScore("GitHub", "gh");
01:01:39.263 VM782:1 Uncaught ReferenceError: quickScore is not defined
    at <anonymous>:1:1

Am i missing something?

**Comment by fwextensions** [comment]
Bloody hell.  I just added that info to the readme and I guess I didn't double-check it.  :|  

If you remove the `browse/` from the URL, it'll work: `<script src="https://unpkg.com/quick-score@0.0.7/dist/quick-score.js"></script>`  The browse paths are just for human consumption, it appears.

Thanks for the bug report!  I'll merge a fix shortly.

**Comment by alvise** [comment]
Thanks, its working now.
Maybe should be noted that in the browser all the functions are inside quickScore so to test the basic example is:

**quickScore**.quickScore("thought", "gh"); 

P.S. Much better than fuse at first sight.

**Comment by fwextensions** [comment]
Good point.  The readme example did show accessing the `QuickScore` class through the global, but using the basic function is probably clearer.

You can compare the search results and speed to fuse and other libs on the demo site: https://fwextensions.github.io/quick-score-demo/
